version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: dsa-backend
    container_name: dsa-backend
    environment:
      - PORT=5005
    ports:
      - 5005:5005
      
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: dsa-frontend
    container_name: dsa-frontend
    ports:
      - 8080:8080